"""PDF report generation with ReportLab."""

import json
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def build_pdf(row) -> BytesIO:
    """Render one `scans` row into an in-memory PDF and return the buffer."""
    ports = json.loads(row["open_ports_json"])
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, title=f"NSAT report {row['target_ip']}")
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Network Security Audit Report", styles["Title"]))
    story.append(
        Paragraph(
            f"Target {row['target_ip']} &middot; {row['created_at']} &middot; generated by NSAT",
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 16))

    story.append(
        Paragraph(
            f"<b>Risk score: {row['risk_score']} / 100 ({row['risk_level']})</b>",
            styles["Heading2"],
        )
    )
    story.append(
        Paragraph(
            "Host status: " + ("Online" if row["is_online"] else "Offline / filtered"),
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 14))

    story.append(Paragraph(f"Open ports ({len(ports)})", styles["Heading2"]))
    if ports:
        data = [["Port", "Service", "Version", "Weight", "Assessment"]]
        for p in ports:
            data.append(
                [
                    f"{p['port']}/{p['protocol']}",
                    p["service"],
                    p["version"],
                    f"+{p['weight']}",
                    Paragraph(p["note"], styles["BodyText"]),
                ]
            )
        table = Table(data, colWidths=[55, 75, 90, 45, 205])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#9ca3af")),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        story.append(table)
    else:
        story.append(Paragraph("No open ports detected on the scanned range.", styles["Normal"]))

    story.append(Spacer(1, 16))
    story.append(Paragraph("Scoring formula", styles["Heading2"]))
    story.append(
        Paragraph(
            "score = min(100, sum of service weights + 3 x (open ports - 3))", styles["Code"]
        )
    )

    doc.build(story)
    buffer.seek(0)
    return buffer
